git add . title: Welocome to Taige's Homepage
page-top-title: Taige
top-section-bg-text: Let's do something for the world
home-subtitle: Taige Luo&ensp;|&ensp;罗泰格
copyright-text: '&copy; Taige 2023-2025. All Rights Reserved.'
