git add . title: Welocome to Taige's Homepage
page-top-title: Taige
top-section-bg-text: Let's do something for the world
home-subtitle: Yourname&ensp;|&ensp;上杉绘梨衣
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
